############################################################
# +------------------------------------------------------+ #
# |                      Model Data                      | #
# +------------------------------------------------------+ #
#                                                          #
#   Deconflict your custom model data here. Make sure      #
#   that the data here correctly corresponds to the data   #
#   in the resource pack. Keep custom model data to no     #
#   than 6 digits. DO NOT change model data once players   #
#   start crafting dyed bundles!                           #
#                                                          #
############################################################

loot:
  enabled: true
  always-drop: true
  drop-rate: 2
