############################################################
# +------------------------------------------------------+ #
# |                  Main Configurations                 | #
# +------------------------------------------------------+ #
############################################################

loot:
  # If enabled, goat will drop horns upon death, according to the rate indicated below.
  enabled: true
  # Provide a non-negative number. The integral part of the number will be the base number
  # of horns to be dropped on each goat's death. The decimal part of the number indicates
  # the rate an extra horn to be dropped. For example, if we have the drop rate as 1.5, 1
  # horn plus 0.5 chance of a second horn will be dropped.
  drop-rate: 0.025
  # If set to true, baby goats will share the same drop rate as adult goats.
  baby: false

horn-use:
  # Any value higher than 100 increases the range of the horn.
  volume: 750
  pitch: 1
  cooldown:
    # The sound lasts roughly 100 ticks.
    duration: 100
    # If set to true, cooldown animation will be applied to all items that are of type iron
    # horse armor for the player.
    show-animation: true

############################################################
# +------------------------------------------------------+ #
# |                      Model Data                      | #
# +------------------------------------------------------+ #
#                                                          #
#   Deconflict your custom model data here. Make sure      #
#   that the data here correctly corresponds to the data   #
#   in the resource pack. DO NOT change model data once    #
#   players start obtaining goat horns.                    #
#                                                          #
#   Note: You can safely ignore this section if you have   #
#   ItemsAdder installed.                                  #
#                                                          #
############################################################

# Default name of item
name: Goat Horn

# Actual item is an iron horse armor
model-data: 10
